### ISSUE TITLE
Advantage over LLVM from apt?

### ISSUE THREAD

**Issue by NickStrupat** [sol-prog/Clang-in-Docker#1]
Hi there,

I'm curious what advantage there is to this over using `apt`? Something like this seems simpler to me but I'm just trying to understand. Thanks!

```docker
FROM ubuntu
RUN apt update && apt install -y clang-6.0
ENV PATH="/usr/lib/llvm-6.0/bin:${PATH}"
```

**Comment by jbenden** [comment]
An advantage is this method uses the Clang release straight from the Clang project.

Another possible reason is one could create a number of Docker images to test their code over numerous Clang releases, without polluting the system environment.
